version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 50
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"