name: CI Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up NodeJS
      uses: actions/setup-node@v5
      with:
        node-version: '22.x'
    - name: Clean
      run: rm -rf node_modules
    - name: Install dependencies
      run: npm install
    - name: Run build
      run: npm run build